### ISSUE TITLE
I had this error when i tried adding the dependency for this library

### ISSUE THREAD

**Issue by knightcube** [burakeregar/EasiestGenericRecyclerAdapter#3]
Error:(29, 13) Failed to resolve: com.github.burakeregar:EasiestGenericRecyclerAdapter:v1.5
<a href="openFile:C:/Users/Anurag/AndroidStudioProjects/UsingLibraryForRecyclerAdapter/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

How do i fix it?

**Comment by burakeregar** [comment]
Please follow the instructions on the readme file. You should add jitpack dependency to the top gradle file.
